### ISSUE TITLE
Cisco XE devices not being extracted.

### ISSUE THREAD

**Issue by jgedeon120** [inspired/TA-cisco_ios#14]
Changing the following in props.conf for cisco:ios

REPORT-cisco_ios-general = extract_cisco_ios-general, extract_cisco_ios-general-xr, extract_cisco_ios-general-xe, extract_cisco_ios-general-wlc, extract_cisco_ios-general-rfc5424

Then adding to transforms.conf:
[extract_cisco_ios-general-xe]
REGEX = ((?<reported_hostname>\S+)\s)?(?<event_id>\d+):\s(?<event_id2>\d+):\s(?<reliable_time>[.*])?(?<device_time>.+):\s%(?<iosxe>IOSXE)-6-(?<platform>PLATFORM):(?<proccess_name>\S+): QFP:(?<qfp>\d+.\d+) Thread:(?<thread>\d+) TS:(?<ts>\d+) %(?<facility>[A-Z0-9_]+)-((?<subfacility>[A-Z0-2_]_(-?[A-Z_][^-]_))-?)?(?<severity_id>[0-7])-(?<mnemonic>[A-Z0-9_]+):\s(?<message_text>.+)

Basic field extractions are being done as expected.  Deeper extractions still need to be done.

**Comment by inspired** [comment]
Thanks. I updated the code with your contribution.  Please test it :-)
