### ISSUE TITLE
SEC_LOGIN  events do not map correctly

### ISSUE THREAD

**Issue by bworrell1** [inspired/TA-cisco_ios#16]
SEC_LOGIN  events do not map correctly, showing as the timezone of the device, such as EDT.  Appears to be caused when also using the Cisco Security Suite app on the same Splunk indexer.

Potential conflict on the props or transform files?

**Comment by inspired** [comment]
Is this still a problem? Can you list the fields that aren't extracted properly?

**Comment by bworrell1** [comment]
We did a complete revamp of out splunk install, including moving the syslog to a syslog-ng box on a heavy forwarder.  Also removed some apps as we did not think they were useful.  With that process done, the conflicting transforms were removed.  So the message appears to be fine now.
