### ISSUE TITLE
src_interface Field Alias Not Working

### ISSUE THREAD

**Issue by freedombirdone** [inspired/TA-cisco_ios#22]
Using version 2.5.4 of app and TA on Splunk 7.2.0 distributed deployment. 

### **I've found src_interface field alias is not being populated from src_int.**

**props.conf**
`
FIELDALIAS-cisco_ios-interface = src_int AS src_interface, dest_int AS dest_interface, interface AS dest_interface, cdp_local_interface AS src_interface, cdp_remote_interface AS dest_interface
`

**Search query from port flapping dashboard widget**
`
eventtype="cisco_ios-port_down" OR eventtype="cisco_ios-port_up" product IN (IOS) index IN (*) | stats count, latest(port_status) AS port_status, latest(src_interface_description) AS description BY host,src_interface | sort -count | table host,src_interface,port_status,description,count
`

### **Also, I've noticed the vendor_message_text field is not being populated either.**

**Search query from diagnostics dashboard widget:**
`
eventtype="cisco_ios-diag" product IN (IOS) index IN (*) | eval eventcode=facility + "-" + severity_id + "-" + mnemonic | stats count AS Count, latest(_time) AS _time, latest(severity_id) AS severity_id by host, eventcode, vendor_message_text | lookup cisco_ios_severity severity_id | sort +severity_id,-Count | table _time, host, eventcode, vendor_message_text, severity_id_and_name, Count
`

**Comment by inspired** [comment]
Can you test with 867547e (latest) as well as with the latest cisco_ios app?

**Comment by inspired** [comment]
Resolved as the field extractions now extract src_interface directly. No aliases involved
